# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55b566209b9b4ce05a22ab0ded3a88c1a9c3831ea9d776521be9a04cf7bd692ac2b76ad8afd9617ec24c4740b73759a98222f0bef0c4ee68facfe5dad7965e4e

test:
  secret_key_base: a8dee4b644639712e1196fc3555ca5a44c11828e9d43394ebfa0cc5bcf8a15567e90af67955cc820e1f59e19d45b95461c360e5758eea1176ee69d09dbd4fe72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
